### ISSUE TITLE
[Font Request] Noto Sans SC

### ISSUE THREAD

**Issue by pinglu85** [KyleAMathews/typefaces#100]
Hi Kyle,

Thanks for the great work!

I want to use [Noto Sans SC](https://fonts.google.com/specimen/Noto+Sans+SC) in my project. Is it possible to add this font? 

Thank you very much.

**Comment by KyleAMathews** [comment]
All typefaces on google fonts are automatically handled for ya :-)

https://www.npmjs.com/package/typeface-noto-sans-sc
