### ISSUE TITLE
[Font Request] B612

### ISSUE THREAD

**Issue by marvinrabe** [KyleAMathews/typefaces#103]
See: http://b612-font.com/

**Comment by KyleAMathews** [comment]
That looks great! It doesn't look like it's on fontsquirrel so the way to get this added is to PR a script that I can run to create the font package e.g. like https://github.com/KyleAMathews/typefaces/blob/master/scripts/package-from-fontsquirrel.js and other scripts in that folder.

**Comment by bomholtm** [comment]
It's on Google Fonts and therefore already added :wink: https://github.com/KyleAMathews/typefaces/tree/master/packages/b612
