### ISSUE TITLE
Poppins woff2 files included as base64 strings in Gatsby

### ISSUE THREAD

**Issue by MarkosKon** [KyleAMathews/typefaces#104]
I'm using **typeface-poppins** with **Gatsby** and I noticed that the .woff2 files are inlined in the `@fontface` rule at the document's head. This obviously results to a huge html file. The .woff2 files are present in the **node_modules** but are not copied in **public/static/** folder during build, only the .woff files are there. The woff2 files for Poppins are pretty small ~= 8kb compared to other fonts. Maybe that's the reason? Is there something we can do to fix this?

**Comment by MarkosKon** [comment]
Gatsby inlines font files [less than 10kb](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack-utils.js), so you'll have to edit the webpack config and replace that limit in `gatsby-node.js`:

```js
// gatsby-node.js
exports.onCreateWebpackConfig = ({ actions, getConfig }) => {
  const config = getConfig()
  const fontRule = config.module.rules.find(rule =>
    String(rule.test).includes("woff")
  )
  // Poppins files are 8kb and more.
  fontRule.use[0].options.limit = 7000
  actions.replaceWebpackConfig(config)
}
```

Useful links:
- [replaceWebpackConfig action](https://www.gatsbyjs.org/docs/actions/#replaceWebpackConfig)
- [Adding a Custom Webpack Config](https://www.gatsbyjs.org/docs/add-custom-webpack-config/)
- [Webpack url-loader](https://webpack.js.org/loaders/url-loader/)

**Comment by harrygreen** [comment]
Thanks @MarkosKon - this has saved me.
