### ISSUE TITLE
[Error] B612 Mono not found

### ISSUE THREAD

**Issue by bomholtm** [KyleAMathews/typefaces#111]
```sh
$ npm install --save typeface-b612-mono
npm ERR! code E404
npm ERR! 404 Not Found: typeface-b612-mono@latest
```

Not sure what's going on 😅

**Comment by KyleAMathews** [comment]
NPM keeps thinking it's spam :-D

Emailed their support to let us in.

<img width="1440" alt="screenshot 2019-03-05 20 55 30" src="https://user-images.githubusercontent.com/71047/53856952-33954200-3f89-11e9-8acc-c107c66282b8.png">

**Comment by KyleAMathews** [comment]
They hooked me up and the package is now published.

**Comment by bomholtm** [comment]
Thank you for all your efforts... That's great!
