### ISSUE TITLE
Metropolis is missing Extra Bold and Black variants

### ISSUE THREAD

**Issue by hackel** [KyleAMathews/typefaces#123]
Probably just an oversight, but these additional weights are missing from the typeface-metropolis package.

**Comment by KyleAMathews** [comment]
Not an oversight, a bug! Fixed in https://github.com/KyleAMathews/typefaces/commit/6e37703fa9897992d633b3f24acf518173fd97d1 and I re-released metropolis with all the weights. Thanks for the report!

**Comment by gustavopch** [comment]
@KyleAMathews Was https://www.npmjs.com/package/typeface-metropolis updated with the fixed version?
