### ISSUE TITLE
[Font Request] DM Sans

### ISSUE THREAD

**Issue by jsnrynlds** [KyleAMathews/typefaces#130]
This is great, thank you.

Please could you add the beautiful Google font [DM Sans](https://fonts.google.com/specimen/DM+Sans) when you get a chance.

**Comment by garrickf** [comment]
Wanna say that it's out now! https://www.npmjs.com/package/typeface-dm-sans

**Comment by jsnrynlds** [comment]
Nice one @garrickf  🖖
