### ISSUE TITLE
Roboto cyrillic

### ISSUE THREAD

**Issue by dbelovol** [KyleAMathews/typefaces#133]
How to add Cyrillic to typefaces roboto? 
I’ve discovered that only Latin version is maintained.

**Comment by cmahte** [comment]
According to the project page at github... Latin, Greek, and Cyrillic are
all supported, but they produce subset fonts for web use. It stands to
reason you stumbled across a Latin only subset.  There should be better
marking when a specific file is a subset, but that's not a discussion for
here.

The Roboto font is sourced here: https://github.com/google/roboto/

**Comment by dbelovol** [comment]
Thanks a lot. I realize that it’s not right place for my question. In fact, I don’t know where it is. 
I’ve installed roboto with 
npm install —save typeface-roboto and then used webpack. 
And only Latin subset is presented. The question is - is it possible to install Cyrillic subset like aforementioned Latin?

**Comment by CyanoFresh** [comment]
@dbelovol how did you solve this?

**Comment by dbelovol** [comment]
I did not. I load desired fonts from Cdn.
