### ISSUE TITLE
[Font Request] Inter UI

### ISSUE THREAD

**Issue by paakay** [KyleAMathews/typefaces#138]

**Comment by paakay** [comment]
A **free** variable font from https://rsms.me/inter/. Lots of glyph and styles and legible at small font sizes. Ideal for mobile phones.

**Comment by paakay** [comment]
Available on FontSquirrel at [Inter](https://www.fontsquirrel.com/fonts/inter)

**Comment by KyleAMathews** [comment]
Thanks @paakay! Published now! https://www.npmjs.com/package/typeface-inter

**Comment by talentlessguy** [comment]
@KyleAMathews for some reason when I try to use `"Inter"` in CSS it doesn't work.
