### ISSUE TITLE
Bundle size seems very large?

### ISSUE THREAD

**Issue by jeznag** [KyleAMathews/typefaces#15]
Hi, any tips on reducing the bundle size? I used typeface-lato and ended up with a bundle size of 4.43MB (2.39MB after Gzip).

All I have in entry.js is:
```
 require('typeface-lato');
```

Webpack config:
```
const CompressionPlugin = require('compression-webpack-plugin');
module.exports = {
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader:'style!css!'
      },
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' },
    ],
  },
  output: {
    filename: 'bundle.js',
  },
  plugins: [
    new CompressionPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.js$|\.html$/,
      threshold: 10240,
      minRatio: 0.8
    })
  ]
}
```

**Comment by KyleAMathews** [comment]
Don't use url loader. Use the file loader instead. The URL loader is
inlining every file format of the font which is why your bundle is so huge.
If you use file loader, the browser will only load one type (for most
browsers now woff2).

What you should inline if possible is the resulting CSS as that'll
significantly speed up loading the fonts if your browser can avoid the
extra CSS request.

**Comment by jeznag** [comment]
Cool that works. I'm guessing subsetting is not a focus for now? Although the individual font files are small now, my service worker cache size has bloated by 4MB as I can't find an easy way of determining which font file relates to Lato Regular which is the only subset I want to use.

For now Google fonts + runtime caching seems like a better approach for me. If there was a way to subset, I'd be keen to use Typefaces.

**Comment by jeznag** [comment]
Probably worth closing this one. Consider updating docs as per PR. Will move discussion to subset issue.

**Comment by KyleAMathews** [comment]
Your service worker should only precache woff2 as any browser that supports service workers also will support woff2. So don't precache woff, ttf, eot, svg.
