### ISSUE TITLE
fonts arent loading using webpack and fontfaceobserver

### ISSUE THREAD

**Issue by hendrikeng** [KyleAMathews/typefaces#16]
Hey @KyleAMathews ,

thanks for your awesome work, i was trying to implement it in a project with
[fontfaceobserver](https://github.com/bramstein/fontfaceobserver) and webpack,
it does all work if i implement it using the google font url in my app.scss , but as soon as i import the typeface node module it doesn't throwing : 

> Uncaught (in promise) A {family: "Output Sans", style: "normal", weight: 400, stretch: "normal"}

thats the entry.js ...i have no idea why whats causing it to be honest: 
```

// Load Open Sans typeface
import 'typeface-open-sans';

// import CSS to bundle it with webpack
import '../scss/app.scss';

const FontFaceObserver = require('fontfaceobserver');

const openSans = new FontFaceObserver('Open Sans', {
  style: 'normal',
  weight: 400,
});

openSans.load().then(() => {
  console.log('Open Sans has loaded'); ´
});

```

**Comment by KyleAMathews** [comment]
Hmmm not sure what's happening. I can't see why it'd have anything to do with typefaces however so [your issue in fontfaceobserver](https://github.com/bramstein/fontfaceobserver/issues/96) is more likely to be fruitful. If there is something wrong here please let us all know!
