### ISSUE TITLE
typeface-muli 1.1.3 font rendering issue

### ISSUE THREAD

**Issue by pachuka** [KyleAMathews/typefaces#169]
Ran into a strange issue when upgrading `typeface-muli` 0.0.71 -> 1.1.3. For some reason $ sign's render incorrectly in the new version.

**1.1.3:**
![image](https://user-images.githubusercontent.com/3280602/76865898-c1149e80-6839-11ea-8daf-4f1d0e187c4a.png)

**0.0.71**
![image](https://user-images.githubusercontent.com/3280602/76865964-d4c00500-6839-11ea-8306-b0f0fc861910.png)

**Comment by jeffreymeng** [comment]
I'm having this issue too. The capital A's are also broken.
Here's the result when I upload the muli-latin-400.woff from the repo  to fontdrop:
<img width="878" alt="2020-03-19_19-56-36" src="https://user-images.githubusercontent.com/15185258/77132212-db0dd700-6a1b-11ea-8325-c5fb45549dae.png">

Here's what it should be (uploaded the ttf file from google fonts):
<img width="973" alt="2020-03-19_19-56-29" src="https://user-images.githubusercontent.com/15185258/77132229-e52fd580-6a1b-11ea-9d0d-d061668560ad.png">

**Comment by marsaldev** [comment]
Same with "Quicksand"

**Comment by ThomasKuhlmann** [comment]
Similar problem with "Maven Pro" - couldn't reproduce an issue with the dollar sign, but the A is distorted as well:

![Screenshot 2020-04-30 at 19 26 59](https://user-images.githubusercontent.com/35376024/80745701-97c57e80-8b18-11ea-977f-e02213039ceb.png)

**Comment by marsaldev** [comment]
I've solved using previous version

**Comment by meold** [comment]
is there a fix in version 1.1.4?

**Comment by marsaldev** [comment]
@meold I don't think so ^^"

**Comment by pReya** [comment]
Same here, even though I downloaded the font directly from Google. So this is a bug that needs to be fixed by Google / the font author.

**Comment by dmitrizzle** [comment]
Related: #209
I'm using an older version now, which doesn't have this version.

**Comment by pReya** [comment]
Just use https://github.com/fontsource/fontsource instead

**Comment by pachuka** [comment]
Migrated to fontsource awhile ago.
