### ISSUE TITLE
Gidole incorrect font-style

### ISSUE THREAD

**Issue by benperiton** [KyleAMathews/typefaces#18]
When loading the 'typeface-gidole' webpack throws an error becuase font-style is missing:

Module build failed:
      font-style: ;
                ^
          Style declaration must contain a value

https://github.com/KyleAMathews/typefaces/blob/master/packages/gidole/index.css#L4

**Comment by benperiton** [comment]
Scrap that, works if I use @import "~typeface-gidole/index.css"; instead of @import "~typeface-gidole";

**Comment by KyleAMathews** [comment]
Huh interesting. Which module builder are you using that uses `~`? Glad you figured it out!
