### ISSUE TITLE
typeface-montserrat references files that don't exist.

### ISSUE THREAD

**Issue by derickkemp** [KyleAMathews/typefaces#23]
index.css in montserrat contains references to

files/montserrat-latin-300italic.svg
files/montserrat-latin-700italic.svg
files/montserrat-latin-800.svg

These files are not present in the files directory that house all the other fonts.

This is preventing webpack with file-loader from building.

**Comment by Lucianovici** [comment]
@KyleAMathews great job implementing this!

We need to find a way of figuring out what files are available and put a `src: url(...)` only if a file exists.

Thinking about updating this https://github.com/KyleAMathews/typefaces/blob/master/scripts/create-package-from-google-font-id.js

Any suggestions?

So far I just use my own css version excluding the missing file(s) and import that instead, so it won't break the webpack compiler/builder.

**Comment by KyleAMathews** [comment]
Try installing the new version https://github.com/KyleAMathews/typefaces/commit/d527d21133c359801755ba5bbd92f075be28977e should have fixed it.

**Comment by Lucianovici** [comment]
Thank you! It works.
