### ISSUE TITLE
typeface-exo-2 references non existent svg files

### ISSUE THREAD

**Issue by ohcibi** [KyleAMathews/typefaces#26]
When using exo-2 with webpack or angular-cli the pack won't build as the `index.css` file references svg file that are not existent in the npm-package. The `files` directory only contains `.svg.mtd` files. Is this on purpose or should the `index.css` actually reference those `.mtd` files? I could PR the latter.

**Comment by KyleAMathews** [comment]
👍 
republished exo-2 with what should be correct tags. There'd been some changes with Google Fonts not distributing SVG files anymore so we had to update things recently.

**Comment by ohcibi** [comment]
n1! But why have you removed the .eot sources?

**Comment by KyleAMathews** [comment]
AFAIK Google isn't distributing those anymore. I didn't have a ton of time to investigate and since I don't support old IEs it was easiest to remove them. If you want to modify our scripts so that they add EOTs when they're available, happy to republish fonts with EOTs back in.

**Comment by dmfrancisco** [comment]
I noticed this with another font, Montserrat:
```
Module not found: Can't resolve './files/montserrat-latin-200.eot'
```

And indeed the file is not there, just a `.eot.mtd` file:

<img width="266" alt="mtd-file" src="https://user-images.githubusercontent.com/212106/29241122-163db76c-7f6b-11e7-9e83-9f46c392113e.png">

The Google Fonts CSS doesn't include the EOT either:
https://fonts.googleapis.com/css?family=Montserrat:200

Thank you for creating this project @KyleAMathews! 👏

**Comment by KyleAMathews** [comment]
Montserrat is updated.
