### ISSUE TITLE
Add League Spartan

### ISSUE THREAD

**Issue by dougajmcdonald** [KyleAMathews/typefaces#29]
Hi Kyle,

Any chance you could add 'League Spartan' to the packages? 

https://www.theleagueofmoveabletype.com/league-spartan

I'd be happy to do it myself if I knew what to do!

I have my gatsby develop and build working fine with fonts included via `url('the font');` but in production something is going awry, so looking for another way to handle webfonts.

**Comment by KyleAMathews** [comment]
Added `typeface-league-spartan`! LIke I wrote [here](https://github.com/KyleAMathews/typefaces/issues/30#issuecomment-327006416) it's pretty easy to add new typefaces as long as they're on Font Squirrel.

**Comment by dougajmcdonald** [comment]
Thanks Kyle, great support
