### ISSUE TITLE
Scope packages under @typeface?

### ISSUE THREAD

**Issue by rohanthacker** [KyleAMathews/typefaces#3]
@KyleAMathews Great repo! Thank you for sharing!

I had a thought about the distribution of these typefaces, would you be open to hosting them on the npm registry under the @typeface scope. Assuming you create the @typography user on npm,  the packages can then be distributed via `npm i @typeface/font-family` which i find to be cleaner than the conventional prefix

**Comment by KyleAMathews** [comment]
Thanks! Hope it proves useful!

I'm somewhat indifferent to using typeface-* or @typeface/* for namespacing but since namespace-* is by far the main convention right now in projects like this (babel, react, gulp, grunt, webpack, etc.) I'll just stick with that for familiarity's sake.
