### ISSUE TITLE
PR or issue for adding a typeface?

### ISSUE THREAD

**Issue by ocean** [KyleAMathews/typefaces#30]
Hi Kyle, love your work 👍

Do you take pull requests to add typefaces to this project? Or would you prefer a request via issue (as you already have your own process created to generate and package the files and release them etc.)?

**Comment by KyleAMathews** [comment]
We don't store the actual font files in Git so a PR to add a font needs to either be instructions on [using one of our existing scripts](https://github.com/KyleAMathews/typefaces/tree/master/scripts)—we have integration with Google Fonts and Font Squirrel. All Google Fonts should be on here and I've manually added a bunch that are hosted on Font Squirrel.

So yeah, check Font Squirrel first and see if it's there. If they do host a webfont kit, then I just need to run the script locally to add it. If it's not there, then either PR a script to fetch the font from another source or manually create a font kit using Font Squirrel and create an issue with the zip file attached and I can take that to create a Typeface package for it.
