### ISSUE TITLE
how to avoid roundtrip to svr?

### ISSUE THREAD

**Issue by brandonmp** [KyleAMathews/typefaces#32]
I was playing w/ the [Google Lighthouse extension](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=en) & I noticed the typefaces I'd added from this project were loaded in second trip to the server:

![image](https://user-images.githubusercontent.com/14139991/30224993-d6da2fda-949e-11e7-97b2-4e5652448ab2.png)

Looking @ [Gatsby's site ](https://www.gatsbyjs.org/) (below), it looks like fonts are loaded in the first trip.

![image](https://user-images.githubusercontent.com/14139991/30225045-110e6c7a-949f-11e7-8ae6-1e94f8ccf55b.png)

I'm assuming the Gatsby site uses typefaces project for fonts. Was there any special step you took to get the fonts on the first round trip?

To load the fonts, I'm simply calling them via requires in `layouts/index.js`:

```
require('typeface-lato');
require('typeface-ubuntu');
```

Then, using the [gatsby-plugin-typograhy](https://www.npmjs.com/package/gatsby-plugin-typography), I just declare the fonts:

```
headerFontFamily: ['Ubuntu', 'sans-serif'],
bodyFontFamily: ['Lato', 'serif'],
```

**Comment by brandonmp** [comment]
hm-maybe this is just a function of my font faces being hosted on cloudfront (courtesy of netlify)?

more info from dev tools:

gatsbyjs.org:
![image](https://user-images.githubusercontent.com/14139991/30225807-d1b652ce-94a1-11e7-911b-e6c01d0a4bec.png)


mine:
![image](https://user-images.githubusercontent.com/14139991/30225880-0a3db56a-94a2-11e7-8ac9-bd22e993de5e.png)

**Comment by KyleAMathews** [comment]
Yeah, it just looks weird because of cloudfront. FWIW, using a CDN with Netlify doesn't help much as they're already a CDN and with Cloudfront you've introduced a second domain now with its own DNS lookups, SSL negotiations, etc.

**Comment by brandonmp** [comment]
oh that's netlify's doing. afaik they pluck the static stuff from the project post-build & stash them on cloudfront

i think it's part of their auto-optimization or something? idk but point is well taken, i'll see how it goes w/o the optimizations. thanks kyle
