### ISSUE TITLE
typeface-roboto parsing error

### ISSUE THREAD

**Issue by zeorin** [KyleAMathews/typefaces#35]
`typeface-roboto` seems to suffer from the same problem as `typeface-roboto-condensed` did in #27.

![roboto_parsing_error](https://user-images.githubusercontent.com/1187078/31165059-d369b1b8-a8e9-11e7-9de7-250fa7ac1071.png)

**Comment by KyleAMathews** [comment]
Just updated the typeface-robot package! Lemme know if it's not working still.

**Comment by zeorin** [comment]
@KyleAMathews I just installed version `0.0.41`. Unfortunately still getting the same error.

**Comment by KyleAMathews** [comment]
Looks like a webpack config error actually https://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts

Are you seeing this problem in Gatsby by chance? I haven't had trouble there but would want to fix it if that's where you're having trouble.
