### ISSUE TITLE
typeface-pt-sans references non-existant files

### ISSUE THREAD

**Issue by emilyemorehouse** [KyleAMathews/typefaces#36]
Similar to #26, PT Sans has 3 files that have the `.mtd` extension and cause them to not be found:
- pt-sans-latin-400.eot.mtd
- pt-sans-latin-400.svg.mtd
- pt-sans-latin-700.eot.mtd

From what I gathered from the previous issue, this is just something that @KyleAMathews can regenerate, but let me know if there's anything I can do to help!

**Comment by KyleAMathews** [comment]
Just made another release earlier of google fonts including pt-sans. Lemme know if it's still not working!
