### ISSUE TITLE
Cooper Hewitt CSS declaration doesn't work

### ISSUE THREAD

**Issue by Grsmto** [KyleAMathews/typefaces#37]
Hi!
The font `Cooper Hewitt` doesn't work because it has 2 `src` declaration as seen there: https://github.com/KyleAMathews/typefaces/blob/master/packages/cooper-hewitt/index.css#L4

If you remove one, it works fine again.

Thanks!

**Comment by KyleAMathews** [comment]
Updated and republished the package. Thanks!
