### ISSUE TITLE
List of supported fonts

### ISSUE THREAD

**Issue by damianobarbati** [KyleAMathews/typefaces#38]
@KyleAMathews is there a list of fonts published over npm within this project?

**Comment by KyleAMathews** [comment]
Yes, look in the packages directory https://github.com/KyleAMathews/typefaces/tree/master/packages

**Comment by Offirmo** [comment]
Could we have a "visual" list to see how they look like? Maybe auto-generated in a `gh-pages` branch?

That would be awesome!
