### ISSUE TITLE
[font request] IBM Plex

### ISSUE THREAD

**Issue by fk** [KyleAMathews/typefaces#40]
https://ibm.github.io/type/
https://github.com/IBM/type/

**Comment by fk** [comment]
Forgot http://www.carbondesignsystem.com/style/typography/overview 😍

**Comment by KyleAMathews** [comment]
I think their npm package might already work out of the box?

**Comment by KyleAMathews** [comment]
Never seen carbon before, nice!

**Comment by thomaskuntzz** [comment]
I love this font and I'd love to be able to use it in Gatsby! I tried to add it with the official NPM package but I just can't figure out how to make it work... **Does anyone know how to do this?** Or maybe there is a plan to add it soon to typefaces?

**Comment by KyleAMathews** [comment]
Look in the scripts folder. You could PR a new script for this font to create its package. That'd be great to see!

**Comment by thomaskuntzz** [comment]
Thanks for such a quick answer! I'd love to do it, except I have no idea how this whole thing works, even after looking at how the repo is structured and after reading the scripts...

**Comment by fk** [comment]
@thomaskuntzz I haven't tried so myself yet, but what @KyleAMathews mentioned in https://github.com/KyleAMathews/typefaces/issues/40#issuecomment-345415308 should work: Use their NPM package and import the CSS it comes with: https://github.com/IBM/type/#how-to-use

**Comment by thomaskuntzz** [comment]
Yes, I know about that, I've been trying to make this work for almost a while, but just installing the NPM package and putting the link to their CSS in the `<head>` via Helmet won't work...

**Comment by fk** [comment]
@thomaskuntzz Gave it a shot and it's working! 🎉 

* Install the package with `yarn add @ibm/type`.
* Open `src/layouts/index.js` and add `import "@ibm/type/css/ibm-type.min.css`.

Then you should be able to use `IBM Plex Sans` or `IBM Plex Mono` as `font-family` in your CSS (or e.g. in `src/utils/typography.js`).

**Comment by fk** [comment]
Yay! Happy to help! 🙌

> but all the links to the font files' locations were broken...

If you take a look at how the font files are referenced, you'll see that the paths are relative, e.g. https://github.com/IBM/type/blob/4aae4cb385b90220d77b1e2396027d0f993099ec/css/ibm-type.css#L5

Importing the CSS file lets Webpack resolve those correctly, while including that CSS file in HTML would require the "fonts" folder (and its contents) to exist at the correct location, relative to the HTML document in which you included the CSS (on the run and struggling with teh English, I hope that made sense! ;-)).

**Comment by fk** [comment]
My explanation actually was a bit off (so much it made me blush a little) – sorry for that! 🙄😳 
Updated my original comment!

**Comment by dougajmcdonald** [comment]
The IBM Plex series and now on google webfonts, could you add them Kyle?, I added a separate issue but will close that in favour of this comment:

https://fonts.google.com/?query=ibm

#61

**Comment by KyleAMathews** [comment]
@dougajmcdonald good to know they're on google fonts! I'll re-run the script to create google fonts packages to add them.

**Comment by KyleAMathews** [comment]
Just published the three ibm packages!

**Comment by fk** [comment]
🎉

**Comment by utkarshkukreti** [comment]
Hi @KyleAMathews! Could you please re-run the script once? It seems like "IBM Plex Sans" (not the Condensed version) was added after you ran the script. Thanks!
