### ISSUE TITLE
Only load used font weights

### ISSUE THREAD

**Issue by mikeriley131** [KyleAMathews/typefaces#43]
Is it possible to only load the weights of the font that are actually being used? Seems wasteful to load all font weight variants when I'm only actually using one or two of them.

**Comment by KyleAMathews** [comment]
Done! That's what browsers do already :-)

**Comment by mikeriley131** [comment]
Sorry to bother you. Yesterday I was seeing all weights of the fonts load. Now I'm just seeing what I'm using. Weird.

**Comment by wcandillon** [comment]
@KyleAMathews Thank you for this great project 🙌🏻Are you 100% positive that the browser only loads the necessary font weights? 🤔It feels like it would be hard to determine that upfront but I could be wrong.

**Comment by KyleAMathews** [comment]
100% :-)

**Comment by wcandillon** [comment]
haha ok 😅

**Comment by wcandillon** [comment]
@KyleAMathews Thank you for your support 🙌🏻 I have a last question: is it possible to make sure nothing is displayed before the font is loaded?

**Comment by KyleAMathews** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by wcandillon** [comment]
Thank you for your continuous support 🙌🏻

**Comment by tiagocpontesp** [comment]
I have nothing against url() inlining the fonts, so they definitely ARE getting bundled in my case.

**Comment by tiagocpontesp** [comment]
> I have nothing against url() inlining the fonts, so they definitely ARE getting bundled in my case.
From now on I'm against url() inlining and i'm using the file-loader. :p
