### ISSUE TITLE
Typeface: Lora not finding .woff files

### ISSUE THREAD

**Issue by loganpowell** [KyleAMathews/typefaces#52]
Hi Kyle! Sorry to be a pest. It's not a big deal (I'll just switch out the font), but just FYI, it seems that 'typeface-lora` is broken. Here's my error:

```
./node_modules/typeface-lora/index.css
Module not found: Can't resolve './files/lora-latin-400.woff' in 'C:\Users\surface\Projects\Bootcamp\census\graphql\raw_typeface_test\node_modules\typeface-lora'
```

I've created a test repository that zero's in on the font, as `typeface-roboto` works, where `typeface-lora` doesn't:

https://github.com/loganpowell/RAW_Typeface_Test/blob/master/src/index.js#L7

**Comment by KyleAMathews** [comment]
I just republished all google font files so this should be fixed 👍 

Thanks for the bug report!

**Comment by loganpowell** [comment]
Thank you!

**Comment by loganpowell** [comment]
Confirmed. Working!
