### ISSUE TITLE
Material-Icons font?

### ISSUE THREAD

**Issue by andrewaylett** [KyleAMathews/typefaces#55]
Using Gatsby with react-md, I've got two fonts loading from Google fonts, but one's an icon font -- Material Icons -- and doesn't look like it's packaged.  It looks like it's not listed on fonts.google.com, which I suspect is the immediate reason it's not included here?  The other is Roboto, which is easy :).

If you're happy to have icon fonts included, I'm happy to do the work to include them. But some advice on what approach you'd prefer to take would be very welcome.

Reference is https://fonts.googleapis.com/css?family=Material+Icons

**Comment by KyleAMathews** [comment]
Seems like it's not a normal Google Font as it doesn't show up here: https://fonts.google.com/

In any case, I don't recommend using fonts for icons. It's much easier, especially with React, to use the SVG directly as you load a lot less data into your site/app. Try out https://www.npmjs.com/package/react-icons which has all popular open source icon sets and lets you import icons as components.
