### ISSUE TITLE
Suggestion: Use NPM scoped packages

### ISSUE THREAD

**Issue by joeskeen** [KyleAMathews/typefaces#56]
@KyleAMathews, Hey just wanted to say thanks for all the work you put into typefaces, after doing a lot of fruitless searching this seems like it really is the way to go with NPM installing open source fonts into projects.

Just thought I would put this out as a suggestion.  With NPM's scoped packages, it makes it easy to predict package names and trust that you are getting what you intend to.  For example, if I want to install the router for Angular, I `npm install @angular/router`.  If I want the TypeScript definitions for JQuery, I `npm install @types/jquery`.  I think it would be super awesome if anyone could install a typeface using `npm install @typeface/open-sans` or something similar.  This could really become a standard way of acquiring fonts from NPM.  (At the time of writing the NPM username `typeface` and `typefaces` are both available.)

**Comment by KyleAMathews** [comment]
I'm pretty indifferent to scoped vs. non-scoped packages. They didn't exist when I started this project and I'm not sure there's a lot of reason to switch right now. That being said, they are becoming more popular and it could make sense to switch especially if we ever do a new major release in the future w/ breaking changes.

I registered @typefaces — someone already has @typeface
