### ISSUE TITLE
IBM Plex Serif Latin 700 missing

### ISSUE THREAD

**Issue by Brixy** [KyleAMathews/typefaces#63]
Hi!

Thanks for your efforts, Kyle!

Just noticed hat `ibm-plex-serif-latin-700.woff2` and `ibm-plex-serif-latin-700.woff` (with corresponding CSS) are missing. Is this intended?

Thanks

**Comment by KyleAMathews** [comment]
Just ran the script again and published new versions for IBM Plex Serif/Sans!
