### ISSUE TITLE
[Font request] Courier Prime family

### ISSUE THREAD

**Issue by julientaq** [KyleAMathews/typefaces#64]
Hey!
The courier prime family is a good alternative to our classic courier font.
Here is the link from Quote Unquote apps: https://quoteunquoteapps.com/courierprime/

And the link to what you can find in fontsquirrel: https://www.fontsquirrel.com/fonts/courier-prime?q%5Bterm%5D=courier+prime&q%5Bsearch_check%5D=Y

My wish is to use the Courier Prime Sans for the text editor we're building :D

Thanks!

**Comment by wangsongiam** [comment]
I'm looking into it too. I could give help adding a package but looks like this repo doesn't have a similar PR.

**Comment by julientaq** [comment]
hey @KyleAMathews Did you get that message?

**Comment by julientaq** [comment]
Thanks! :+1:
