### ISSUE TITLE
[Font Request] Fira Code

### ISSUE THREAD

**Issue by danielkov** [KyleAMathews/typefaces#78]
It is a great font that supports ligatures and I would love to see it up here. I can create a PR if possible.

**Comment by Siilwyn** [comment]
Posterity: https://github.com/tonsky/FiraCode

**Comment by KyleAMathews** [comment]
That'd be great! Is it on fontsquirrel? If so, it's easy to import from there. Otherwise, you can create a custom script for creating the font package and I can run that.

**Comment by Siilwyn** [comment]
Hmmm... it is on fontsquirrel but it is using an old unmaintained version.

**Comment by azdanov** [comment]
There is an NPM package: https://www.npmjs.com/package/firacode. Might be helpful.

**Comment by Soullivaneuh** [comment]
I don't see the interest to add firacode as it already exists as official NPM package.

**Comment by Siilwyn** [comment]
Because that package is not being maintained by the looks of it.

**Comment by Soullivaneuh** [comment]
@Siilwyn What do you mean?

It is maintained from official repo: https://github.com/tonsky/FiraCode/blob/b1eec5cdacf37a19577c441834b895dd56a68c3f/package.json#L2

**Comment by Siilwyn** [comment]
Last version is published 2 years ago on npm.

**Comment by dsvensson** [comment]
@KyleAMathews 

> That'd be great! Is it on fontsquirrel? If so, it's easy to import from there. Otherwise, you can create a custom script for creating the font package and I can run that.

Could you elaborate on what this script would do exactly it would be easier to get contributions. Getting Fira Code (or Hasklig, or Iosevka, or all of them) packaged would be really nice.

**Comment by johnridesabike** [comment]
It looks like the official Fira Code NPM package got a version bump a few weeks ago (the first in 2 years).

**Comment by Microflash** [comment]
@KyleAMathews Fira Code is now available on Google Fonts (https://fonts.google.com/specimen/Fira+Code), so hopefully, you should be able to pull it up.

**Comment by hasparus** [comment]
I think this issue can be closed.

https://github.com/KyleAMathews/typefaces/tree/master/packages/fira-code
