### ISSUE TITLE
another approach to the problem

### ISSUE THREAD

**Issue by kapouer** [KyleAMathews/typefaces#8]
Example: i'm using my own [bundler](https://github.com/kapouer/bundledom)(which, admittedly, could use webpack under the hood) and i came up with an alternative solution: downloading at bundle time. It's not yet perfect but i think it's easier to generalize, unless the remote service sets up some kind of protection (unless the legality of this is questionable).

**Comment by KyleAMathews** [comment]
This definitely works! I like my solution as a) I want to define all project dependencies with NPM and b) there are times when you're not online but want to work on a project so having all your assets locally is very handy.
