### ISSUE TITLE
Variable fonts

### ISSUE THREAD

**Issue by dmitrizzle** [KyleAMathews/typefaces#83]
Is there any planned support for variable fonts?

[Most modern browsers](https://caniuse.com/#search=variable%20fonts) can render those, implementing which would save a lot more bandwidth and requests than subsetting.

To be honest I haven't looked into this in-depth, and, perhaps it works out of the box. If so, please let me know and I will do due diligence to add a "How-To" to the docs.

If it requires some work to build, I'd be happy to make a PR. But before going forward, I'd like a word from someone who's more in-the-know about `typefaces`.

Thank you!

**Comment by KyleAMathews** [comment]
Variable fonts use the same type of font files as normal fonts so there's nothing new we'd need to do here.

**Comment by mightyiam** [comment]
Are you sure, @KyleAMathews ?
