### ISSUE TITLE
Loading partial font variations

### ISSUE THREAD

**Issue by mmlumba** [KyleAMathews/typefaces#89]
Hi,

Is there a way to only import certain font weights and styles into an application? Since I'm working with material-ui and it only requires 300/400/500 font weights I'd like to use only those instead. Thanks!

**Comment by KyleAMathews** [comment]
Browsers only load fonts as needed. E.g. even if you specify an italic version of a font or a heavy weight, as long as it's not used on a page, the browser won't load the font files for the different unused variants.

**Comment by matt-snider** [comment]
@KyleAMathews But they will get included into the bundle (e.g. via webpack) if `require()`'d or `import`ed as suggested in the README. @mmlumba Wouldn't it work to just do:

```es6
```

**Comment by matt-snider** [comment]
Thanks for the response Kyle. I will look into that
