### ISSUE TITLE
do you need require.js ? 

### ISSUE THREAD

**Issue by d3netxer** [KyleAMathews/typefaces#9]
I notice you write:

require("typeface-open-sans")

what if you don't have require.js? Should I add it require.js to my web app, or can I add the font another way?

**Comment by KyleAMathews** [comment]
Each Typeface package ships with web-ready font files for each weight & style within the typeface. It also ships with a css file that if you're using certain web building tools like webpack (properly configured), to use the typeface in your project, you only need to require the css file.

It's possible you could get requiring working with require.js — but I'm not familiar with the tool. Perhaps https://github.com/guybedford/require-css could get you there.

But even if your web builder can't be configured to automatically include fonts, you could still use Typefaces to partially automate adding fonts as you could install the typefaces you want and then copy those files into the appropriate place.

You can see the file structure for one of the typefaces here:

https://unpkg.com/typeface-open-sans@0.0.21/
